---
title: Mobilon
timezone: UTC
collections:
  phones:
    title: Phones
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: phones
  values:
    Brand:
    Is in stock: 
    Thumbnail image:
    images:
    - 
author: Revaz Zakalashvili
tagline: Mobilon - Used Mobile Phones
description: ''
keywords: ''
email: contact@mobilon.ge
linkedin: https://www.linkedin.com/
twitter: https://twitter.com/
github: https://github.com/
repository: 
baseurl: ''
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
