---
title: Mobilon
timezone: UTC
collections:
  phones:
    title: Phones
    output: true
    permalink: "/:path"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: phones
  values:
    layout: phone
    Brand: 
    Is in stock: 
    Is in sale: 
    Thumbnail image: 
    price: 
    new price: 
    images:
    - 
author: Revaz Zakalashvili
tagline: Used Mobile Phones
description: 
keywords: 
email: contact@mobilon.ge
linkedin: https://www.linkedin.com/
twitter: https://twitter.com/
github: https://github.com/
repository: 
baseurl: 
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
